import { chromium } from "/Users/shipeilin/projects/mine/giteehelper/node_modules/playwright/index.mjs";
const BASE = "http://127.0.0.1:8899";
const browser = await chromium.launch({ channel: "chrome", headless: true, args: ["--use-gl=swiftshader", "--enable-unsafe-swiftshader"] });
const page = await browser.newPage({ viewport: { width: 1680, height: 1000 } });
const errors = [];
page.on("pageerror", e => errors.push(e.message));
await page.goto(BASE + "/", { waitUntil: "networkidle" });
await page.fill('input[autocomplete="username"]', process.env.PU);
await page.fill('input[autocomplete="current-password"]', process.env.PW);
await page.click(".login-form button");
await page.waitForSelector(".sidebar");
await page.goto(BASE + "/repo", { waitUntil: "networkidle" });
await page.waitForSelector(".repo-canvas canvas");
await page.waitForTimeout(6500);
await page.screenshot({ path: process.env.OUT || "/tmp/repo-v2.png" });
const box = async (sel) => { const b = await page.locator(sel).first().boundingBox().catch(() => null); return b ? `y=${Math.round(b.y)} w=${Math.round(b.width)} h=${Math.round(b.height)}` : "无"; };
console.log("画布 :", await box(".repo-canvas-wrap"));
console.log("侧栏 :", await box(".repo-sidebar"));
console.log("负责人面板:", await box(".repo-sidebar .panel:nth-child(1)"));
console.log("接入状态 :", await box(".repo-sidebar .panel:nth-child(2)"));
console.log("图例     :", await box(".repo-sidebar .panel:nth-child(3)"));
console.log("页面总高 :", await page.evaluate(() => document.documentElement.scrollHeight), " 视口:", await page.evaluate(() => window.innerHeight));
console.log("错误:", errors.length ? errors.slice(0,3).join(" || ") : "无");
await browser.close();
