import { chromium } from "/Users/shipeilin/projects/mine/giteehelper/node_modules/playwright/index.mjs";
const BASE = "http://127.0.0.1:8899";
const browser = await chromium.launch({ channel: "chrome", headless: true, args: ["--use-gl=swiftshader", "--enable-unsafe-swiftshader"] });
const page = await browser.newPage({ viewport: { width: 1680, height: 1000 } });
await page.goto(BASE + "/", { waitUntil: "networkidle" });
await page.fill('input[autocomplete="username"]', process.env.ADMIN_USERNAME);
await page.fill('input[autocomplete="current-password"]', process.env.ADMIN_PASSWORD);
await page.click(".login-form button");
await page.waitForSelector(".sidebar");
await page.goto(BASE + "/repo", { waitUntil: "networkidle" });
await page.waitForSelector(".repo-canvas canvas");
await page.waitForTimeout(6000);
const dist = () => page.evaluate(() => { const c = window.__repoDebug.graph.camera().position; return Math.round(Math.hypot(c.x, c.y, c.z)); });
const span = () => page.evaluate(() => { const d = window.__repoDebug, g = d.graph; const n = d.nodes.filter(x => x.x !== undefined); const p = n.map(x => g.graph2ScreenCoords(x.x, x.y, x.z)); return Math.round((Math.max(...p.map(q=>q.y)) - Math.min(...p.map(q=>q.y))) / g.height() * 100); });
console.log("初始     : 相机距离", await dist(), " 占高", await span() + "%");
await page.click('button:has-text("重置视角")');
await page.waitForTimeout(1500);
console.log("点重置后 : 相机距离", await dist(), " 占高", await span() + "%");
const r = await page.evaluate(() => { const d = window.__repoDebug; const n = d.nodes.filter(x => x.x !== undefined); return Math.round(Math.max(...n.map(x => Math.hypot(x.x, x.y, x.z)))); });
console.log("节点最大半径:", r, " 期望相机距离 ≈", Math.round(r * 1.18 / Math.tan(50 * Math.PI / 360)));
await browser.close();
